apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-cluster-deepmalamittal
--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app-deployment
  namespace: kubernetes-cluster-deepmalamittal
  labels:
    app: dotnet-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: dotnet-app
  template:
    metadata:
      labels:
        app: dotnet-app
    spec:
      containers:
        - name: dotnet-app-pod
          image: deepmalamittal89/devopskubernetes:i-deepmalamittal-master-latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
          - configMapRef:
              name: app-settings
          - secretRef:
              name: secret-info
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-app-service
  namespace: kubernetes-cluster-deepmalamittal
spec:
  type: LoadBalancer
  selector: 
    app: dotnet-app
  ports:    
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "app-settings"
  namespace: kubernetes-cluster-deepmalamittal
  labels:
    app: "app-settings"
data:
  YEAR: "2022"
  COMPANY: "Nagarro"
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-info
  namespace: kubernetes-cluster-deepmalamittal
type: Opaque
data:
  UserName: "YWRtaW4="
  Password: "UGFzc3cwcmQ="
