apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app-deployment
  namespace: kubernetes-cluster-deepmalamittal
  labels:
    app: dotnet-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: dotnet-app
  template:
    metadata:
      labels:
        app: dotnet-app
    spec:
      containers:
        - name: dotnet-app-pod
          image: deepmalamittal89/devopskubernetes:i-deepmalamittal-master-latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-app-service
  namespace: kubernetes-cluster-deepmalamittal
spec:
  type: LoadBalancer
  selector: 
    app: dotnet-app
  ports:    
  - protocol: TCP
    port: 80
    targetPort: 80
